### ISSUE TITLE
Unable to sync from toggle to clockify

### ISSUE THREAD

**Issue by sjohn92** [mikerourke/transfermyti.me#46]
Unable to sync from toggle to clockify. It fetches from toggl, but gives and error from clockify immediately after start.

**Comment by mikerourke** [comment]
@sjohn92 It looks like Clockify made some changes to their API (I can’t delete a project now until I archive it first). I’ll do some digging over the next couple of days and fix the breaking changes. I’ll ping you when the fixes are deployed. Sorry about that!

**Comment by mikerourke** [comment]
Hey @sjohn92, quick update: last week/weekend was kind of bananas so I didn't get a chance to look into this issue. I'm going to try knocking it out this week. I apologize for the delay.

**Comment by mikerourke** [comment]
@sjohn92 I just fixed the issue with being unable to delete a Clockify project, but I didn't run into any other errors. I just upgraded the dependencies and released a new version. Before any release, I transfer data between test accounts to verify that everything is working correctly. Here's the full process:

1. Transfer a bunch of data from a test Toggl account to a test Clockify account
2. Delete all the data from the Toggl account
3. Transfer all the data from the Clockify account back to Toggl
4. Delete all the data from the Clockify account

By "delete all the data", I mean "delete everything but the workspaces". So there are a few questions I have regarding the errors you're getting:

1. Are you transferring tasks? I'm not able to test task transfer because it's a paid feature on Toggl.
2. Are you the only user on your account, or is it an organization/company account?
3. If it is an org/company account, are you trying to transfer data associated with a different user?
4. Are you trying to transfer a lot of data (e.g. > 1,000 time entries)?

Most of the issues that get submitted are related to multi-user transfer. I've been meaning to add support for that feature since I released this tool (~3 years ago). However, it's a pretty massive undertaking and I don't have the bandwidth :(.

Anyway, let me know if the answer to any of those 4 questions is "yes" so I can try to narrow down the issue.

**Comment by sjohn92** [comment]
Hello Mike,
Thanks a lot for checking this. I'm using a personal account and trying to transfer time entries from toggl to clockify which used to work before without any issues. Please find below my answers for your queries.
1. Are you transferring tasks? I'm not able to test task transfer because it's a paid feature on Toggl.
No, I'm transferring only time entries
2. Are you the only user on your account, or is it an organization/company account?
Yes its a personal account in toggl free version
3. If it is an org/company account, are you trying to transfer data associated with a different user?
NA
4. Are you trying to transfer a lot of data (e.g. > 1,000 time entries)?
I see it has about 587 time entries.
![image](https://user-images.githubusercontent.com/88151541/145695568-5b01c3e1-2181-4fd3-9035-aa48807ad30c.png)
When I try to transfer, it immediately gives me an error as below
![image](https://user-images.githubusercontent.com/88151541/145695607-e5f9b9d7-6f77-4bc7-8d66-66637e165621.png)

**Comment by mikerourke** [comment]
@sjohn92 I'm guessing there's an issue with the data, which is a little harder to troubleshoot without being able to see it. Just to give you some insights on how the tool works, it:

1. Pulls all of the projects, tags, clients, time entries, etc. from Toggl
2. Pulls all of the same entities from Clockify
3. Converts the data from both sources into records with the same field names (i.e. a Toggl time entry might have a `project_id`, while Clockify has a `projectId`), so I create a `Project` record with a `projectId` field and which tool that record is associated with
4. Tries to associate the IDs of the entities from Toggl with the entities from Clockify (if a project named "Some Project" exists on Toggl and Clockify, it includes that `projectId` in the payload for a time entry being transferred)

Some of the issues that users have encountered in the past are caused by a disparity between the source data and target data, which is why I added functionality to delete all the data from either tool and try again. If you were able to transfer everything _but_ the time entries, I might be able to spot the issue in the network request that's returning the `400` error. If you haven't spent too much time making changes on the Clockify account, could you try deleting everything from Clockify and trying the transfer again?

If it still fails, could you send me the payload from the failing network request? If you need help getting that data, I can write up a quick instruction guide for you.

**Comment by sjohn92** [comment]
Hi Mike,
I deleted all entries from clockify and tried to transfer again and I'm still getting the same error. I was able to delete all entries from Clockify though. I'm using free version of both Toggl and Clockify, I'm not sure if it's a new change from Clockify, I saw something like this at https://clockify.me/toggl-importer that for importing time entries, you may need a paid subscription. I was unable to import manually from Clockify also.
![image](https://user-images.githubusercontent.com/88151541/145736519-4ee4aa4d-1845-417b-87cb-41bca47cc45b.png)

**Comment by mikerourke** [comment]
@sjohn92 Are you only transferring time entries, or are you also transferring projects?
